## Numpy array and basics
numpy

In [2]:
import numpy as np

## Creating array from list

In [4]:
arr_1d = np.array([1,2,3,4,5])
print("1D-Array: ",arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D-Array: ", arr_2d)


1D-Array:  [1 2 3 4 5]
2D-Array:  [[1 2 3]
 [4 5 6]]


## List vs Numpy array

In [6]:
py_list = [1,2,3]
print("python list multiplication with 2: ", py_list*2)

np_array = np.array([1,2,3])
print("Numpy array multiplication with 2: ", np_array*2)

# operation time
import time

sl = time.time()
py_list = [i*2 for i in range(1000000)]
print("List operation time: ", time.time()-sl)

sn = time.time()
np_array = np.arange(1000000) * 2
print("Numpy operation time: ", time.time()-sn)

python list multiplication with 2:  [1, 2, 3, 1, 2, 3]
Numpy array multiplication with 2:  [2 4 6]
List operation time:  0.06504154205322266
Numpy operation time:  0.00795602798461914


## creating array from scratch

In [10]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("Ones array: \n", ones)

full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0,10,2)
print("Sequence: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.40766774 0.8146737  0.1956084 ]
 [0.16110726 0.07245186 0.02748519]]
Sequence: 
 [0 2 4 6 8]


## Vector, matrix and tensor

In [ ]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
                   [5,6,8]])
print("Matrix: \n", matrix)

tensor = np.array([[1,2],
                  [3,4],
                  [5,6],
                  [7,8]])
print("Tensor: \n", tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [5 6 8]]


TypeError: array() takes from 1 to 2 positional arguments but 4 were given